on:
  push:
    paths:
      - .github/workflows/build_levilamina.yml
      - src/**
      - xmake.lua
  pull_request:
    paths:
      - .github/workflows/build_levilamina.yml
      - src/**
      - xmake.lua
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v4
        with:
          name: levilamina-windows-x64-${{ github.sha }}
          path: |
            build/windows/x64/release/LeviLamina.dll
            build/windows/x64/release/LeviLamina.lib
            build/windows/x64/release/LeviLamina.pdb

  build-debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m debug -p windows -v -y

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v4
        with:
          name: levilamina-debug-windows-x64-${{ github.sha }}
          path: |
            build/windows/x64/debug/LeviLamina.dll
            build/windows/x64/debug/LeviLamina.lib
            build/windows/x64/debug/LeviLamina.pdb

  build-with-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y --tests=true

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v4
        with:
          name: levilamina-with-tests-windows-x64-${{ github.sha }}
          path: |
            build/windows/x64/release/LeviLamina.dll
            build/windows/x64/release/LeviLamina.lib
            build/windows/x64/release/LeviLamina.pdb

  build-debug-with-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m debug -p windows -v -y --tests=true

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v4
        with:
          name: levilamina-debug-with-tests-windows-x64-${{ github.sha }}
          path: |
            build/windows/x64/debug/LeviLamina.dll
            build/windows/x64/debug/LeviLamina.lib
            build/windows/x64/debug/LeviLamina.pdb

  check-code:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          choco install llvm -y --version=17.0.6

      - name: clang-format
        run: |
          Get-ChildItem src/ -Filter *.cpp -Recurse | ForEach-Object { clang-format -i -Werror $_.FullName }
          Get-ChildItem src/ -Filter *.h -Recurse | ForEach-Object { clang-format -i -Werror $_.FullName }

      - name: clang-tidy
        run: |
          Get-ChildItem src/ -Filter *.cpp -Recurse | ForEach-Object { clang-tidy -p build -header-filter=src/ $_.FullName }
          Get-ChildItem src/ -Filter *.h -Recurse | ForEach-Object { clang-tidy -p build -header-filter=src/ $_.FullName }
