on:
  push:
    paths:
      - .github/workflows/build_levilamina.yml
      - scripts/localbdslibrary.lua
      - src
      - xmake.lua
  pull_request:
    paths:
      - .github/workflows/build_levilamina.yml
      - scripts/localbdslibrary.lua
      - src
      - xmake.lua
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v3
        with:
          path: |
            ~/AppData/Local/.xmake
            .xmake
          key: xmake-levilamina-windows-x64-${{ github.sha }}
          restore-keys: |
            levilamina-xmake-windows-x64

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y --ccache=n

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v3
        with:
          name: levilamina-windows-x64-${{ github.sha }}
          path: |
            build/windows/x64/release/LeviLamina.dll
            build/windows/x64/release/LeviLamina.lib
            build/windows/x64/release/LeviLamina.pdb
