on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v3
        with:
          path: |
            ~/AppData/Local/.xmake
            .xmake
          key: xmake-liteloader-windows-x64-${{ github.sha }}
          restore-keys: |
            liteloader-xmake-windows-x64

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y --ccache=n

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v3
        with:
          name: liteloader-windows-x64-${{ github.sha }}
          path: |
            build/windows/x64/release/LiteLoader.dll
            build/windows/x64/release/LiteLoader.lib
            build/windows/x64/release/LiteLoader.pdb

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: liteloader-windows-x64-${{ github.sha }}
          path: bin

      - run: |
          cp CHANGELOG.md LICENSE.md README.md bin/

      - name: Archive release
        run: |
          cd bin
          zip -r ../liteloader-windows-x64.zip *
          cd ..

      - uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            liteloader-windows-x64.zip
