on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v3
        with:
          name: levilamina-windows-x64-${{ github.sha }}
          path: |
            build/windows/x64/release/LeviLamina.dll
            build/windows/x64/release/LeviLamina.lib
            build/windows/x64/release/LeviLamina.pdb

  build-debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m debug -p windows -v -y

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v3
        with:
          name: levilamina-debug-windows-x64-${{ github.sha }}
          path: |
            build/windows/x64/debug/LeviLamina.dll
            build/windows/x64/debug/LeviLamina.lib
            build/windows/x64/debug/LeviLamina.pdb

  upload-to-release:
    needs:
      - build
      - build-debug
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download release artifact
        uses: actions/download-artifact@v3
        with:
          name: levilamina-windows-x64-${{ github.sha }}
          path: release/release/lib

      - name: Download debug artifact
        uses: actions/download-artifact@v3
        with:
          name: levilamina-debug-windows-x64-${{ github.sha }}
          path: release/debug/lib

      - name: Make include directory
        run: |
          python scripts/make_include.py

      - name: Copy include
        run: |
          cp -r include release/release/
          cp -r include release/debug/

      - name: Copy README, LICENSE and CHANGELOG
        run: |
          cp CHANGELOG.md COPYING COPYING.LESSER README.md release/release/
          cp CHANGELOG.md COPYING COPYING.LESSER README.md release/debug/

      - name: Archive release release
        run: |
          cd release/release/
          zip -r ../../levilamina-windows-x64.zip *
          cd ../../

      - name: Archive debug release
        run: |
          cd release/debug/
          zip -r ../../levilamina-debug-windows-x64.zip *
          cd ../../

      - name: Calculate SHA256
        id: calculate-sha256
        run: |
          echo release=$(sha256sum levilamina-windows-x64.zip | awk '{print $1}') >> $GITHUB_OUTPUT
          echo debug=$(sha256sum levilamina-debug-windows-x64.zip | awk '{print $1}') >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v1
        with:
          append_body: true
          body: |
            | File | SHA256 |
            | ---- | ------ |
            | levilamina-windows-x64.zip | ${{ steps.calculate-sha256.outputs.release }} |
            | levilamina-debug-windows-x64.zip | ${{ steps.calculate-sha256.outputs.debug }} |
          files: |
            levilamina-windows-x64.zip
            levilamina-debug-windows-x64.zip
